<?php
$event=is_array($event??null)?$event:null;
$selectedClasses=is_array($selectedClasses??null)?$selectedClasses:[];
$selectedStudents=is_array($selectedStudents??null)?$selectedStudents:[];
$editing=!empty($event['id']); $audience=$event['publico']??'todos';
$dateValue=static fn($value)=>$value?date('Y-m-d\TH:i',strtotime($value)):'';
?>
<div class="mb-8"><a href="<?= URL ?>/admin/calendario-escolar" class="text-blue-600">← Voltar</a><h2 class="text-2xl font-bold mt-3"><?= $editing?'Editar evento':'Novo evento' ?></h2></div>
<form method="post" action="<?= URL ?>/admin/calendario-escolar<?= $editing?'/'.(int)$event['id']:'' ?>" class="bg-white rounded-xl shadow p-6 space-y-6"><input type="hidden" name="_token" value="<?= htmlspecialchars($csrf_token) ?>">
<div><label class="block text-sm font-medium mb-1">Título *</label><input name="titulo" required maxlength="255" value="<?= htmlspecialchars($event['titulo']??'') ?>" class="w-full rounded-lg border-slate-300"></div><div><label class="block text-sm font-medium mb-1">Descrição</label><textarea name="descricao" rows="5" class="w-full rounded-lg border-slate-300"><?= htmlspecialchars($event['descricao']??'') ?></textarea></div>
<div class="grid md:grid-cols-3 gap-4"><div><label class="block text-sm font-medium mb-1">Categoria</label><select name="categoria" class="w-full rounded-lg border-slate-300"><?php foreach(['evento','reunião','prova','feriado','passeio','apresentação'] as $category): ?><option <?= ($event['categoria']??'evento')===$category?'selected':'' ?>><?= $category ?></option><?php endforeach; ?></select></div><div><label class="block text-sm font-medium mb-1">Prioridade</label><select name="prioridade" class="w-full rounded-lg border-slate-300"><?php foreach(['normal'=>'Normal','importante'=>'Importante','urgente'=>'Urgente'] as $value=>$label): ?><option value="<?= $value ?>" <?= ($event['prioridade']??'normal')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><div><label class="block text-sm font-medium mb-1">Local</label><input name="local" value="<?= htmlspecialchars($event['local']??'') ?>" class="w-full rounded-lg border-slate-300"></div></div>
<div class="grid md:grid-cols-2 gap-4"><div><label class="block text-sm font-medium mb-1">Início *</label><input type="datetime-local" name="inicio_em" required value="<?= $dateValue($event['inicio_em']??null) ?>" class="w-full rounded-lg border-slate-300"></div><div><label class="block text-sm font-medium mb-1">Fim</label><input type="datetime-local" name="fim_em" value="<?= $dateValue($event['fim_em']??null) ?>" class="w-full rounded-lg border-slate-300"></div></div><label class="flex gap-2"><input type="checkbox" name="dia_inteiro" value="1" <?= !empty($event['dia_inteiro'])?'checked':'' ?>> Evento de dia inteiro</label>
<div><label class="block text-sm font-medium mb-2">Público *</label><div class="flex flex-wrap gap-5"><label><input type="radio" name="publico" value="todos" <?= $audience==='todos'?'checked':'' ?>> Todos</label><label><input type="radio" name="publico" value="turmas" <?= $audience==='turmas'?'checked':'' ?>> Turmas</label><label><input type="radio" name="publico" value="alunos" <?= $audience==='alunos'?'checked':'' ?>> Alunos específicos</label></div></div>
<div id="calendar-classes" class="<?= $audience==='turmas'?'':'hidden' ?>"><select name="turmas[]" multiple size="7" class="w-full rounded-lg border-slate-300"><?php foreach($classes as $c): ?><option value="<?= (int)$c['id'] ?>" <?= in_array((int)$c['id'],$selectedClasses,true)?'selected':'' ?>><?= htmlspecialchars($c['nome']) ?></option><?php endforeach; ?></select></div><div id="calendar-students" class="<?= $audience==='alunos'?'':'hidden' ?>"><select name="alunos[]" multiple size="10" class="w-full rounded-lg border-slate-300"><?php foreach($students as $s): ?><option value="<?= (int)$s['id'] ?>" <?= in_array((int)$s['id'],$selectedStudents,true)?'selected':'' ?>><?= htmlspecialchars($s['nome'].' · '.($s['turma_nome']??'Sem turma')) ?></option><?php endforeach; ?></select></div>
<button class="btn-primary-custom px-6 py-3 rounded-lg font-semibold"><?= $editing?'Salvar e notificar alteração':'Publicar e notificar' ?></button></form>
<script>const rs=document.querySelectorAll('[name=publico]'),cs=document.getElementById('calendar-classes'),ss=document.getElementById('calendar-students');function t(){const v=document.querySelector('[name=publico]:checked').value;cs.classList.toggle('hidden',v!=='turmas');ss.classList.toggle('hidden',v!=='alunos')}rs.forEach(r=>r.addEventListener('change',t));</script>
