<?php
$formatNotaPdf = static function ($value, int $places): string {
    return is_numeric($value) ? number_format((float) $value, $places, ',', '.') : ((string) $value !== '' ? (string) $value : '-');
};
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><style>
@page{margin:10mm} body{font-family:'DejaVu Sans',sans-serif;color:#1f2937;font-size:8pt;margin:0}.student{page-break-after:always;page-break-inside:avoid}.student.last{page-break-after:auto}.report-header{display:table;width:100%;border-bottom:2px solid #5b21b6;padding-bottom:7px;margin-bottom:10px}.logo-cell{display:table-cell;width:105px;vertical-align:middle}.logo-cell img{max-width:95px;max-height:52px}.title-cell{display:table-cell;vertical-align:middle;padding-left:10px}.title-cell h1{font-size:15pt;margin:0 0 3px}.meta{color:#6b7280}.student-head{border:1px solid #9ca3af;background:#f3f4f6;padding:5px 7px}.signature{float:right;width:245px}.line{display:inline-block;width:175px;border-bottom:1px solid #374151}table.grades{width:100%;border-collapse:collapse}table.grades th,table.grades td{border:1px solid #d1d5db;padding:3px 5px}table.grades th{background:#f9fafb;text-align:center}table.grades td:not(:first-child){text-align:center}.observation{margin-top:9px;border:1px solid #d1d5db;background:#f8fafc;padding:7px}.observation-title{font-weight:bold;margin-bottom:3px}.observation-text{white-space:pre-wrap;line-height:1.35}.footer{position:fixed;bottom:-5mm;right:0;color:#9ca3af;font-size:7pt}
</style></head><body>
<?php $alunosPdf = array_values((array) ($relatorio['alunos'] ?? [])); foreach ($alunosPdf as $alunoIndex => $aluno): ?>
<div class="student <?= $alunoIndex === count($alunosPdf) - 1 ? 'last' : '' ?>">
<div class="report-header"><?php if (!empty($logo_data)): ?><div class="logo-cell"><img src="<?= htmlspecialchars((string) $logo_data) ?>" alt="Logo"></div><?php endif; ?><div class="title-cell"><h1>Notas da Coordenação</h1><div class="meta"><?= htmlspecialchars((string) ($relatorio['evento_nome'] ?? 'Boletim')) ?><?php if (($relatorio['nota_abaixo_de'] ?? null) !== null): ?> · Média final abaixo de <?= htmlspecialchars(number_format((float) $relatorio['nota_abaixo_de'], 1, ',', '.')) ?><?php endif; ?><?php if (($relatorio['materias_exibicao'] ?? 'todas') === 'abaixo'): ?> · Somente matérias abaixo do corte<?php endif; ?></div></div></div>
<div class="student-head"><strong><?= htmlspecialchars((string) $aluno['nome']) ?></strong> · Turma: <?= htmlspecialchars((string) $aluno['turma']) ?><?php if ((string) $aluno['ra'] !== ''): ?> · RA: <?= htmlspecialchars((string) $aluno['ra']) ?><?php endif; ?><?php if ($incluir_assinatura): ?><span class="signature">Assinatura: <span class="line"></span></span><?php endif; ?></div>
<table class="grades"><thead><tr><th style="text-align:left">Matéria</th><?php foreach ($relatorio['columns'] as $column): ?><th><?= htmlspecialchars((string) $column['label']) ?></th><?php endforeach; ?></tr></thead><tbody>
<?php foreach ((array) $aluno['materias'] as $materia): ?><tr><td><?= htmlspecialchars((string) $materia['nome']) ?></td><?php foreach ($relatorio['columns'] as $column): ?><td><?= htmlspecialchars($formatNotaPdf($materia['notas'][$column['codigo']] ?? null, (int) $relatorio['decimal_places'])) ?></td><?php endforeach; ?></tr><?php endforeach; ?>
</tbody></table><?php if (trim((string) ($aluno['observacao'] ?? '')) !== ''): ?><div class="observation"><div class="observation-title">Observação da coordenação</div><div class="observation-text"><?= htmlspecialchars((string) $aluno['observacao'], ENT_QUOTES, 'UTF-8') ?></div></div><?php endif; ?></div>
<?php endforeach; ?><div class="footer">Gerado em <?= htmlspecialchars((string) $gerado_em) ?></div></body></html>
