-- Documento e endereço completo do aluno

ALTER TABLE `alunos`
  ADD COLUMN `rg` VARCHAR(20) NULL DEFAULT NULL AFTER `cpf`,
  ADD COLUMN `logradouro` VARCHAR(255) NULL DEFAULT NULL AFTER `rg`,
  ADD COLUMN `numero` VARCHAR(20) NULL DEFAULT NULL AFTER `logradouro`,
  ADD COLUMN `complemento` VARCHAR(100) NULL DEFAULT NULL AFTER `numero`,
  ADD COLUMN `bairro` VARCHAR(120) NULL DEFAULT NULL AFTER `complemento`,
  ADD COLUMN `cidade` VARCHAR(120) NULL DEFAULT NULL AFTER `bairro`,
  ADD COLUMN `uf` CHAR(2) NULL DEFAULT NULL AFTER `cidade`,
  ADD COLUMN `cep` VARCHAR(8) NULL DEFAULT NULL AFTER `uf`;
