-- Campos completos para responsáveis (endereço, RG, celular, data_nascimento)

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'rg'), 'ALTER TABLE responsaveis ADD COLUMN rg VARCHAR(20) NULL AFTER cpf', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'celular'), 'ALTER TABLE responsaveis ADD COLUMN celular VARCHAR(20) NULL AFTER telefone', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'data_nascimento'), 'ALTER TABLE responsaveis ADD COLUMN data_nascimento DATE NULL AFTER celular', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'endereco'), 'ALTER TABLE responsaveis ADD COLUMN endereco VARCHAR(255) NULL AFTER data_nascimento', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'numero'), 'ALTER TABLE responsaveis ADD COLUMN numero VARCHAR(20) NULL AFTER endereco', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'complemento'), 'ALTER TABLE responsaveis ADD COLUMN complemento VARCHAR(100) NULL AFTER numero', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'bairro'), 'ALTER TABLE responsaveis ADD COLUMN bairro VARCHAR(120) NULL AFTER complemento', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'cidade'), 'ALTER TABLE responsaveis ADD COLUMN cidade VARCHAR(120) NULL AFTER bairro', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'uf'), 'ALTER TABLE responsaveis ADD COLUMN uf CHAR(2) NULL AFTER cidade', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'cep'), 'ALTER TABLE responsaveis ADD COLUMN cep VARCHAR(9) NULL AFTER uf', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql = (SELECT IF(NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'responsaveis' AND COLUMN_NAME = 'observacoes'), 'ALTER TABLE responsaveis ADD COLUMN observacoes TEXT NULL AFTER cep', 'SELECT 1'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
