-- Rollback: 2026_08_19_turmas_sala_turno.sql

SET @db := DATABASE();

SET @fk := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='turmas' AND CONSTRAINT_NAME='fk_turmas_sala_padrao' AND CONSTRAINT_TYPE='FOREIGN KEY');
SET @sql := IF(@fk>0, "ALTER TABLE `turmas` DROP FOREIGN KEY `fk_turmas_sala_padrao`", 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='turmas' AND COLUMN_NAME='observacoes');
SET @sql := IF(@col>0, "ALTER TABLE `turmas` DROP COLUMN `observacoes`", 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='turmas' AND COLUMN_NAME='sala_padrao_id');
SET @sql := IF(@col>0, "ALTER TABLE `turmas` DROP COLUMN `sala_padrao_id`", 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='turmas' AND COLUMN_NAME='turno');
SET @sql := IF(@col>0, "ALTER TABLE `turmas` DROP COLUMN `turno`", 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='school_locations' AND COLUMN_NAME='capacidade');
SET @sql := IF(@col>0, "ALTER TABLE `school_locations` DROP COLUMN `capacidade`", 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
