<div class="mb-8"><a href="<?= URL ?>/admin/comunicacao-escolar" class="text-blue-600">← Voltar</a><h2 class="text-2xl font-bold mt-3">Nova comunicação</h2><p class="text-slate-500">Será enviada aos responsáveis no app e por push.</p></div>
<form method="post" action="<?= URL ?>/admin/comunicacao-escolar" enctype="multipart/form-data" class="bg-white rounded-xl shadow p-6 space-y-6">
  <input type="hidden" name="_token" value="<?= htmlspecialchars($csrf_token) ?>">
  <div><label class="block text-sm font-medium mb-1">Título *</label><input name="titulo" maxlength="255" required class="w-full rounded-lg border-slate-300"></div>
  <div><label class="block text-sm font-medium mb-1">Mensagem *</label><textarea name="conteudo" rows="7" required class="w-full rounded-lg border-slate-300"></textarea></div>
  <div class="grid md:grid-cols-3 gap-4"><div><label class="block text-sm font-medium mb-1">Prioridade</label><select name="prioridade" class="w-full rounded-lg border-slate-300"><option value="normal">Normal</option><option value="importante">Importante</option><option value="urgente">Urgente</option></select></div><div><label class="block text-sm font-medium mb-1">Expira em</label><input type="datetime-local" name="expires_at" class="w-full rounded-lg border-slate-300"></div><label class="flex items-center gap-2 mt-7"><input type="checkbox" name="permite_resposta" value="1" checked> Permitir resposta</label></div>
  <div><label class="block text-sm font-medium mb-2">Destinatários *</label><div class="flex flex-wrap gap-5"><label><input type="radio" name="publico" value="todos" checked> Todos os responsáveis</label><label><input type="radio" name="publico" value="turmas"> Por turma</label><label><input type="radio" name="publico" value="alunos"> Individual</label></div></div>
  <div id="classes" class="hidden"><label class="block text-sm font-medium mb-1">Turmas</label><select name="turmas[]" multiple size="7" class="w-full rounded-lg border-slate-300"><?php foreach($classes as $class): ?><option value="<?= (int)$class['id'] ?>"><?= htmlspecialchars($class['nome']) ?></option><?php endforeach; ?></select><p class="text-xs text-slate-500 mt-1">Use Ctrl/Cmd para selecionar mais de uma.</p></div>
  <div id="students" class="hidden"><label class="block text-sm font-medium mb-1">Alunos / responsáveis</label><input id="student-filter" placeholder="Pesquisar aluno..." class="w-full rounded-lg border-slate-300 mb-2"><select name="alunos[]" multiple size="10" class="w-full rounded-lg border-slate-300"><?php foreach($students as $student): ?><option value="<?= (int)$student['id'] ?>"><?= htmlspecialchars($student['nome'].' · '.($student['turma_nome']??'Sem turma')) ?></option><?php endforeach; ?></select></div>
  <div><label class="block text-sm font-medium mb-1">Anexos</label><input type="file" name="attachments[]" multiple accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx,.txt" class="w-full rounded-lg border border-slate-300 p-2"><p class="text-xs text-slate-500 mt-1">Até 10 MB por arquivo.</p></div>
  <button class="btn-primary-custom px-6 py-3 rounded-lg font-semibold">Publicar e notificar</button>
</form>
<script>
const radios=document.querySelectorAll('[name=publico]'), classes=document.getElementById('classes'), students=document.getElementById('students');
function target(){const v=document.querySelector('[name=publico]:checked').value;classes.classList.toggle('hidden',v!=='turmas');students.classList.toggle('hidden',v!=='alunos')} radios.forEach(r=>r.addEventListener('change',target));
document.getElementById('student-filter').addEventListener('input',function(){const q=this.value.toLowerCase();document.querySelectorAll('[name="alunos[]"] option').forEach(o=>o.hidden=!o.textContent.toLowerCase().includes(q))});
</script>
